= Sterownik swobodnie programowalny, jako podstawowy element układu sterowania: Koprocesor sieci. Ogólna budowa i zasada działania. Buforowanie transmisji.
Rafał Borowiak gr. 3 <raf.borowiak@gmail.com>
24.01.2016 r.


:doctype: article
:listing-caption: Listing
:pdf-page-size: A4


== Wstęp
Sterowniki swobodnie programowalne, w skrócie *PLC* (and. _Programmable Logic Controllers_)
to najprościej ujmując komputery przemysłowe pod kontrolą systemu operacyjnego czasu rzeczywistego.
W nazwie _sterownik swobodnie programowalny_ człon _sterownik_ określa funkcjonalność tego urządzenia.
Sterowniki PLC mają za zadanie sterowaniem procesami w środowisku przemysłowym na podstawie danych uzyskanych z
czujników pomiarowych poprzez moduły wejściowe, czy na podstawie danych uzyskanych poprzez sieć.
Sterowanie odbywa się za pomocą modułów wyjściowych podłączonych do różnego rodzaju urządzeń wykonawczych.
O tym, że sterownik jest _swobodnie programowalny_ świadczy fakt, że jest on komputerem i wykonuje pewien program,
napisany z myślą o konkretnym systemie i procesie przemysłowym. Program ten może być zmieniany, nawet
bez przerywania pracy sterownika.

Podsumowując podstawową funkcjonalność sterowników programowalnych, urządzenia te:

* zbierają pomiary z czujników i urządzeń pomiarowych poprzez moduły wejściowe, lub pomiary udostępnione poprzez sieć
* przetwarzają zebrane dane zgodnie z wgranym programem
* generują sygnały sterujące do urządzeń wykonawczych poprzez moduły wyjściowe, sterując ten sposób procesem przemysłowym

i dodatkowo:

* udostępniają przetworzone dane poprzez sieć

== Budowa sterownika PLC
Na rynku jest wiele producentów i rodzajów sterowników PLC. Od małych urządzeń,
z małą ilością pamięci i niską sprawnością obliczeniową do dużych sterowników,
które wydajnością nie ustępują najwydajniejszym komputerom ogólnego przeznaczenia.
Sterowniki PLC można podzielić na urządzenia kompatkowe, które integrują
niezbędne elementy sterownika w jednej obudowie, oraz na sterowniki modułowe
które są rozszerzalne za pomocą modułów odpowiadających za daną funkcjonalność.
W sterownikach PLC można wyróżnić następujące elementy:

Moduł zasilania::
Zazwyczaj jest to moduł wymienny, który dostępny jest w wersjach
dostosowanych do różnych napięc zasilania (240V AC, 120V AC, czy 24V DC). Dzięki
temu jeden sterownik PLC bezproblemowo może być użyty w wielu miejscach,
oferujących różne standardy zasilania.
Jednostka centralna (CPU)::
"Serce" każdego komputera, w tym sterownika PLC. Odpowiada za wykonywanie
instrukcji (kodu programu),tym samym za wykonywanie operacji
arytmetyczno-logicznych i za sterowanie przepływem informacji.

Pamięć::
Jednostki pamięci z fizycznego punktu widzenia w sterownikach PLC:

* pamięć ROM zawierająca system operacyjny (tzw. _firmware_)
* pamięć RAM która zawiera wykonywany program, dane programu, obraz wejść i
wyjść sterownika, posiada dodatkowe podtrzymanie bateryjne na wypadek awarii
systemu zasilania
* opcjonalnie pamięć EEPROM czy flash, która także zawiera program użytkownika
(kopia zapasowa programu)

Koprocesor sieci::
Posiada pewne interfejsy sieciowe i umożliwia niezależną komunikację sieciową.
Implementuje protkoły wymiany w danej sieci, zwykle są to protkoły
deterministyczne czasowo.

Moduły wejść::
Ich zadaniem odwzorowanie sygnału elektrycznego w postaci danych cyfrowych.
Zawierają binarne, wejścia cyfrowe, zazwyczaj izolowane galwanicznie za pomocą
układów opto izolatorów, aby dopasować poziomy napięć wejściowych i zabezpieczyć
elektronikę PLC. Mogą też zawierać wejścia analogowe,
próbkujące i przetwarzające sygnały analogowe za pomocą przetwornika
analogowo-cyfrowego.

Moduły wyjść::
Można je podzielić na trzy różne typy:

* wyjścia przekaźnikowe
* wyjścia tranzystorowe
* wyjścia triakowe

Ich zadaniem jest konwersja cyfrowych sygnałów sterujących na sygnały
elektryczne pozwalające na sterowanie elementami zewnętrzynymi takimi jak lampy
czy diody sygnalizujące, zawory i inne.

Elementy te połączone są różnymi magistralami, co umożliwia sprawną wymianę
informacji pomiędzy nimi.

== Cykl pracy PLC
Sterownik PLC jako element rozproszonego systemu czasu rzeczywistego, musi
pracować cyklicznie. Tylko w ten sposób można mówić o determiniźmie czasowym
w środowisku przemysłowym. Podstawowy cykl pracy prostego sterownika PLC
wygląda następująco - najpierw wykonuje on czynności inicjalizujące:

. Test zasilania
. Test pamięci

Następnie rozpoczyna się właściwy cykl działania:

[ditaa]
....
+-------------------------------+
| Test diagnostyczny            |<---+
+-------------------------------+    |
                |                    |
                v                    |
+-------------------------------+    |
| Czytanie stanów wejść         |    |
+-------------------------------+    |
                |                    |
                v                    |
+-------------------------------+    |
| Wykonanie programu użytkowego |    |
+-------------------------------+    |
                |                    |
                v                    |
+-------------------------------+    |
| Obsługa koprocesora sieci     |    |
|(i innych koprocesorów)        |    |
+-------------------------------+    |
                |                    |
                v                    |
+-------------------------------+    |
| Aktualizacja stanów wyjść     |----+
+-------------------------------+
....

Każda z wykonywanych czynności trwa przez pewien czas i wpływa na długość cyklu,
jednak największe znaczenie ma czas realizacji programu, który nie musi być
stały, a więc jego wyznaczenie nie jest kwestią banalną. Ilość wymian
wykonywanych przez koprocesor sieci zależy od długości całego cyklu, i tym samym
wpływa na cykl wymiany informacji w całej sieci.

Na czym polegają kolejne kroki cyklu?

Test diagnostyczny::
Polega na wykonaniu podstawowej diagnostyki określającej czy sterownik PLC
może kontynuować swoją pracę. Wykonywane są np. testy konfiguracji i zasilania
modułów. Sprawdzane jest np. czy możliwa jest komunikacja z modułami, a jeśli
wystąpi poważny błąd to sterownik przechodzi w tryb _STOP_ i informuje o
problemie.

Czytanie stanów wejść::
Stan wejść to podstawowe dane na których operuje sterownik PLC. W tym kroku są
one zapisywane w pamięci. Dlatego też program nie ma dostępu do aktualnych
stanów wejść, a jedynie do ich stanu zapisanego w tej fazie.

Wykonanie programu użytkowego::
Tutaj wykonywany jest jeden obieg programu użytkownika. Tutaj program
przetwarza dane wejściowe i zapisuje wyniki do obszaru pamięci odpowiedzialnego
za przechowywanie danych wyjściowych. Przetwarzane są także dane otrzymane
przez sieć, oraz wywoływane rozkazy wykonania transmisji.

Obsługa koprocesora sieci::
W tej fazie koprocesor sieci wykonuje rozkazy transmisji otrzymane od jednostki
centralnej. Przepisuje także otrzymane z sieci informacje do pamięci, tak aby
w fazie wykonania programu można było z nich skorzystać.

Aktualizacja stanów wyjść::
W tym kroku dane z pamięci przepisywane są do buforów wyjściowych modułów
wyjściowych, co następnie skutkuje uaktualnieniem poziomu elektrycznych sygnałów
na wyjściach.

== Koprocesor sieci
Moduł koprocesora sieci jest istotnym elementem sterownika PLC dla systemów
rozproszonych. To on odpowiada za komunikacje z innymi urządzeniami takimi jak
stacje robocze, czy inne urządzenia PLC poprzez sieć. Wykonuje on dwie
podstawowe czynności:

. Odbiera rozkazy od jednostki macierzystej i na jej podstawie kopiuje żądne
obszary pamięci do bufra, opakowuje je w ramki odpowiednie dla danego protokołu
i w odpowiednim momencie transmituje za pomocą nadajnika.
. Odbiera i dekoduje ramki przychodzące przez sieć, jeśli są przeznaczone
dla obsługiwanego sterownika PLC to przepisuje je do bufora odbiorczego
i w we właściwym momencie do odpowiednego obszaru pamięci.

Zadania te są realizowanie niezależnie od jenostki centralnej. Cykl pracy
sterownika przemysłowego nie jest zsynchronizowany z cyklem obiegu informacji
w sieci. Może to prowadzić do różnego rodzaju problemów w przypadku
niewystarczających parametrów sieci.

=== Rodzaje żądań transmisji
==== Transmisje periodyczne
Jednostka centralna może żądać od koprocesora transmisji danego obszaru pamięci
co pewien interwał czasowy. Żądanie te wysyłane jest jednokrotnie, a koprocesor
dba o mierzenie interwałów i odpowiednie wysyłanie danych. Jednak takie
transmisje nie zawsze muszą być realizowalnej w danej sieci z zadanym protkołem
dostępu. Koprocesor sieci może np. nie mieć tak często dostępu do łącza, z uwagi
na cykl sieci trwający dłużej niż zadany interwał wymian periodycznych. W takim
wypadku odbiorcy danych, otrzymają dane "nieświeże" i jest to sytuacja wysoce
nieporządana.

==== Transmisje wyzwalane
Transmisje wyzwalane to żądania jednokrotnego przesyłu danego obszaru pamięci
jednostki centralne. Między wystąpieniem żądania, a rzeczywistą transmisją,
występuje pewne opóźnienie wynikające znowu z protokołu dostępu, a także z
długości trwania cyklu sterownika, ponieważ odczyt pamięci przez koprocesor
odbywa się dopiero po jego zakończeniu.
